---
:domain: try.puppet.com
:profiles:
    :default:
      :image: agent
      :prerun: pe_classify
      :setup: course_selector
      :postrun: pe_purge
    :docs:
      :image: agent
      :postrun: purge_certs
